### ISSUE TITLE
deze namen zijn zonder enig betekenis

### ISSUE THREAD

**Issue by Theo-denBlanken** [pimhakkert/fro_sass#3]
Je hebt feedback gekregen van **Theo-denBlanken**
op:
```c

@import "help1";
@import "help2";
@import "help3";
@import "help4";
 
```

URL: https://github.com/pimhakkert/fro_sass/blob/master/styles/style.scss

Feedback: tip betere namen bedenken , of becommentariëren.
Mixins mag je gerust mixins noemen hoor.[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"f4c7fd44b1473a891bf3d2fcce99804c1347b00e","path":"styles/style.scss","reviewer":"Theo-denBlanken"}')

**Comment by pimhakkert** [comment]
nieuwe namen gemaakt

**Comment by Theo-denBlanken** [comment]
Als je de sass verandert, deze natuurlijk opniuw naar css compilen. Deze css dan weer uploaden en committen.

**Comment by Theo-denBlanken** [comment]
Als je de sass verandert, deze natuurlijk opniuw naar css compilen. Deze css dan weer uploaden en committen.

met vriendelijke groeten,
-


[ma-logo]
Theo den Blanken
        [Theo] <http://blanken5.home.xs4all.nl/>
docent
Mediadeveloper
Mediacollege Amsterdam  [Twitter] <https://twitter.com/theodenblanken/>  [WordPress] <http://bla.hosts.ma-cloud.nl/>




Op 27 mei 2019, om 09:11 heeft Pim Hakkert <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Closed #3<https://github.com/pimhakkert/fro_sass/issues/3>.
